// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace BBGamelib{
	public class cc3Utils
	{
		public static Bounds ConvertToLocalBounds(Transform transform, Bounds bounds){
			var min = bounds.min;
			var max = bounds.max;
			Vector3 center = bounds.center;
			center = transform.InverseTransformPoint(bounds.center);
			var point1 = transform.InverseTransformPoint(new Vector3(min.x, min.y, min.z));
			var point2 = transform.InverseTransformPoint(new Vector3(min.x, min.y, max.z));
			var point3 = transform.InverseTransformPoint(new Vector3(min.x, max.y, min.z));
			var point4 = transform.InverseTransformPoint(new Vector3(min.x, max.y, max.z));
			var point5 = transform.InverseTransformPoint(new Vector3(max.x, min.y, min.z));
			var point6 = transform.InverseTransformPoint(new Vector3(max.x, min.y, max.z));
			var point7 = transform.InverseTransformPoint(new Vector3(max.x, max.y, min.z));
			var point8 = transform.InverseTransformPoint(new Vector3(max.x, max.y, max.z));
			var result = new Bounds(center,Vector3.zero);
			result.Encapsulate(point1);
			result.Encapsulate(point2);
			result.Encapsulate(point3);
			result.Encapsulate(point4);
			result.Encapsulate(point5);
			result.Encapsulate(point6);
			result.Encapsulate(point7);
			result.Encapsulate(point8);
			return result;
		}
		
	}
}

